version: "3.8"

services:
  dind:
    # Docker-in-Docker service: stores container layers in a named volume (docker-cache)
    image: docker:24-dind
    container_name: project2_dind
    privileged: true
    environment:
      # disable TLS for lab convenience (insecure) -- DO NOT do this in production
      - DOCKER_TLS_CERTDIR=
    volumes:
      - docker-cache:/var/lib/docker
    networks:
      - cicd-net
    expose:
      - "2375" # available to other compose services on the network

  jenkins:
    # Custom Jenkins image (we'll build it below) that contains docker client
    build: ./jenkins
    image: project2_jenkins:latest
    container_name: project2_jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"   # Jenkins UI
      - "50000:50000" # Jenkins agent port
    depends_on:
      - dind
    environment:
      - DOCKER_HOST=tcp://dind:2375
      - DOCKER_TLS_VERIFY=0
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins/init.groovy.d:/var/jenkins_home/init.groovy.d:ro
    networks:
      - cicd-net

volumes:
  jenkins_home:
  docker-cache:

networks:
  cicd-net:
