services:
  dind:
    image: docker:24-dind
    container_name: dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client
      - docker-layer-cache:/var/lib/docker   # Docker layer cache (speeds image builds)
      - jenkins-data:/var/jenkins_home       # optional: persist jenkins files if required
    networks:
      jenkins_net:
        aliases:
          - docker                          # so Jenkins can talk to tcp://docker:2376
    healthcheck:
      test: ["CMD-SHELL", "docker info >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  jenkins:
    build: ./jenkins
    container_name: jenkins
    restart: unless-stopped
    user: root
    depends_on:
      - dind
    environment:
      - DOCKER_HOST=tcp://docker:2376        # points Jenkins to DinD
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "8080:8080"     # Jenkins UI
      - "50000:50000"   # Jenkins agent port
    volumes:
      - jenkins-data:/var/jenkins_home
      - docker-certs-client:/certs/client:ro
    networks:
      - jenkins_net
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/login || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 6

volumes:
  jenkins-data:
  docker-certs-ca:
  docker-certs-client:
  docker-layer-cache:

networks:
  jenkins_net:
    driver: bridge
