version: '3.8'

services:
  dind:
    # Docker-in-Docker service: allows Jenkins to build and run Docker images safely
    image: docker:24-dind
    container_name: project2_dind
    privileged: true                   # required for DinD
    environment:
      - DOCKER_TLS_CERTDIR=             # disable TLS for lab convenience (insecure)
    volumes:
      - docker-cache:/var/lib/docker    # persist Docker layers across container restarts
    networks:
      - cicd-net
    expose:
      - "2375"                          # Docker daemon accessible to other services on the network

  jenkins:
    # Jenkins service that uses DinD to run Docker commands
    build: ./jenkins                     # path to custom Jenkins Dockerfile with Docker CLI installed
    image: project2_jenkins:latest
    container_name: project2_jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"                      # Jenkins UI
      - "50000:50000"                    # Jenkins agent port
    depends_on:
      - dind
    environment:
      - DOCKER_HOST=tcp://dind:2375     # connect Jenkins Docker CLI to DinD service
      - DOCKER_TLS_VERIFY=0              # disable TLS verification (insecure, for lab)
    volumes:
      - jenkins_home:/var/jenkins_home              # persist Jenkins data
      - ./jenkins/init.groovy.d:/var/jenkins_home/init.groovy.d:ro # init scripts
    networks:
      - cicd-net

volumes:
  jenkins_home:
  docker-cache:

networks:
  cicd-net:
